Model ACE_B6_N7_18_rid_lap_1.5, Test bulk_Si_diamond
Test run at 2020-08-19 18:04

model file: ../../models/ACE_B6_N7_18_rid_lap_1.5/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 108, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/ACE_B6_N7_18_rid_lap_1.5/model.py'
